### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "normal",
  "password": "qwer1234"
}

### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "normal",
  "email": "normal",
  "password": "qwer1234"
}
